spring:
  application:
    name: gateway  # Name of your Gateway service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enables dynamic route discovery via Eureka
          lower-case-service-id: true  # Optional, converts service IDs to lowercase
    discovery:
      enabled: true     
       
eureka:
      client:
        service-url:
              defaultZone: http://service-registry:8761/eureka/  # Eureka server URL

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
